apiVersion: v1
kind: Service
metadata:
  name: iskoces-service
  namespace: iskoces
  labels:
    app.kubernetes.io/name: iskoces
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/name: iskoces
    app.kubernetes.io/component: server
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
    protocol: TCP
  - name: mt-http
    port: 5000
    targetPort: mt-http
    protocol: TCP
  type: LoadBalancer

